import { NextResponse } from 'next/server'

import { getSiteConfigMemoryFirst } from '@/lib/site-config-cache'

export const dynamic = 'force-dynamic'
export const revalidate = 0

export async function GET() {
  const cfg = await getSiteConfigMemoryFirst()
  const enabled = cfg?.skillsDebugEnabled === true
  const modeRaw = String(cfg?.skillsAuthMode ?? '').trim().toLowerCase()
  const authMode = modeRaw === 'oauth' || modeRaw === 'apikey' ? modeRaw : 'unconfigured'

  const lines: string[] = []

  lines.push('---')
  lines.push('name: waken-wa-agent-skills')
  lines.push('description: >-')
  lines.push('  Assists with site debugging and configuration changes for Waken personal site.')
  lines.push('  Use when the user asks to modify site settings, adjust theme or branding,')
  lines.push('  or manage content configuration via the Skills admin debug channel.')
  lines.push('metadata:')
  lines.push('  author: waken-wa')
  lines.push('  version: 1.0.0')
  lines.push('  category: development')
  lines.push('  tags: [site-admin, debug, configuration]')
  lines.push('---')
  lines.push('')

  lines.push('# Waken Admin Debug Skill')
  lines.push('')
  lines.push('Manage and debug site configuration for a Waken personal site through a secure Skills channel.')
  lines.push('')

  lines.push('## When to Use')
  lines.push('')
  lines.push('- The user asks you to change site settings (theme, branding, content strategy)')
  lines.push('- The user wants to debug or inspect current backend configuration')
  lines.push('- The user mentions "Skills", "admin debug", or "site config"')
  lines.push('')

  lines.push('## Entry Points')
  lines.push('')
  lines.push('| Endpoint | Purpose |')
  lines.push('|----------|---------|')
  lines.push('| `GET /api/admin/skills/md` | This skill document (static reference) |')
  lines.push('| `GET /api/admin/skills/direct?mode=...` | Runtime status check, OAuth authorize link generation, and token verification |')
  lines.push('')

  lines.push('## Current Status')
  lines.push('')
  lines.push(`- skillsEnabled: **${enabled ? 'true' : 'false'}**`)
  lines.push(`- authMode: **${authMode}**`)
  lines.push('')

  lines.push('## Required Headers')
  lines.push('')
  lines.push('Minimum required headers for Skills-channel requests:')
  lines.push('')
  lines.push('```')
  lines.push('LLM-Skills-Token: YOUR_TOKEN')
  lines.push('# OAuth mode additionally requires:')
  lines.push('LLM-Skills-AI: YOUR_UNIQUE_AI_ID')
  lines.push('```')
  lines.push('')
  lines.push('Optional but recommended headers:')
  lines.push('')
  lines.push('```')
  lines.push('LLM-Skills-Mode: oauth | apikey')
  lines.push('LLM-Skills-AI: YOUR_UNIQUE_AI_ID')
  lines.push('LLM-Skills-Scope: feature | theme | content')
  lines.push('LLM-Skills-Request-Id: ANY_REQUEST_ID')
  lines.push('```')
  lines.push('')

  lines.push('## Step-by-Step Instructions')
  lines.push('')

  lines.push('### Environment Priority (must check first)')
  lines.push('')
  lines.push('If runtime environment provides these values, use them first:')
  lines.push('- `waken-wa-host-url`')
  lines.push('- `waken-wa-host-apikey`')
  lines.push('')
  lines.push('Behavior rules:')
  lines.push('1. Try these two values first as primary host and APIKEY')
  lines.push('2. If they do not work, stop using them and ask the user how to proceed')
  lines.push('3. In most cases, only one credential is needed for Skills writes: APIKEY or OAuth token')
  lines.push('')

  lines.push('### OAuth Flow (requires user confirmation)')
  lines.push('')
  lines.push('1. Call `GET /api/admin/skills/direct?mode=oauth&ai=YOUR_UNIQUE_AI_ID` to get backend-generated authorize link')
  lines.push('2. Read `guide.authorizeLink` from response, then send that link to the user')
  lines.push('3. The user opens the link and confirms in the dialog')
  lines.push('4. Only after user confirmation will a token be issued (valid for 1 hour by default)')
  lines.push('5. The token is bound to your AI ID; multiple tokens can coexist for the same AI')
  lines.push('6. Every OAuth API request MUST include both `LLM-Skills-Token` and `LLM-Skills-AI`')
  lines.push('7. If not authorized or token expired, repeat step 1 to get a fresh authorize link')
  lines.push('')

  lines.push('### APIKEY Flow (no second confirmation)')
  lines.push('')
  lines.push('1. Check your own environment variable for an API key')
  lines.push('2. If missing, check backend configured status via the admin UI')
  lines.push('3. If still missing, instruct the user to configure an APIKEY first (do not proceed)')
  lines.push('4. If key is available, execute immediately without extra confirmation')
  lines.push('')

  lines.push('## Available API Endpoints')
  lines.push('')
  lines.push('After authenticating with the required headers, use these endpoints to read and modify site configuration.')
  lines.push('')

  lines.push('### Read Current Settings')
  lines.push('')
  lines.push('```')
  lines.push('GET /api/admin/settings')
  lines.push('```')
  lines.push('')
  lines.push('Returns `{ success: true, data: { ... } }` with all current configuration fields.')
  lines.push('')

  lines.push('### Export Used Apps JSON')
  lines.push('')
  lines.push('```')
  lines.push('GET /api/admin/activity/apps-export')
  lines.push('```')
  lines.push('')
  lines.push('Default to curl with required headers:')
  lines.push('')
  lines.push('```bash')
  lines.push('curl -s -X GET "${HOST_URL}/api/admin/activity/apps-export" \\')
  lines.push('  -H "LLM-Skills-Token: ${APIKEY}" \\')
  lines.push('  -H "LLM-Skills-Mode: apikey"')
  lines.push('```')
  lines.push('')
  lines.push('Where `HOST_URL` and `APIKEY` should come from `waken-wa-host-url` and `waken-wa-host-apikey` when available.')
  lines.push('')
  lines.push('Returns `{ success: true, data: { version, exportedAt, groups: { pc, mobile } } }`.')
  lines.push('Use this to analyze already-used apps and generate filtering or naming rules.')
  lines.push('')

  lines.push('### Update Settings')
  lines.push('')
  lines.push('```')
  lines.push('PATCH /api/admin/settings')
  lines.push('Content-Type: application/json')
  lines.push('')
  lines.push('{ "fieldName": "newValue", ... }')
  lines.push('```')
  lines.push('')
  lines.push('Send only the fields you want to change. Unspecified fields keep their current values.')
  lines.push('The server enforces the deny list; sending a denied field returns HTTP 403.')
  lines.push('')

  lines.push('### App Rules JSON Import/Export Method')
  lines.push('')
  lines.push('For app rules import/export behavior and normalization strategy, follow:')
  lines.push('- `docs/app-rules-import-export.md`')
  lines.push('')
  lines.push('Rules JSON only covers these fields:')
  lines.push('- `appMessageRules`')
  lines.push('- `appMessageRulesShowProcessName`')
  lines.push('- `appFilterMode`')
  lines.push('- `appBlacklist`')
  lines.push('- `appWhitelist`')
  lines.push('- `appNameOnlyList`')
  lines.push('- `mediaPlaySourceBlocklist`')
  lines.push('')
  lines.push('When applying imported rules via API, send a single PATCH to `/api/admin/settings` containing those fields.')
  lines.push('Default to curl and include `LLM-Skills-*` headers when applying imported JSON.')
  lines.push('')

  lines.push('### Allowed Fields by Category')
  lines.push('')

  lines.push('**Profile and Branding**')
  lines.push('')
  lines.push('| Field | Type | Description |')
  lines.push('|-------|------|-------------|')
  lines.push('| `pageTitle` | string | Site title |')
  lines.push('| `userName` | string | Display name (required) |')
  lines.push('| `userBio` | string | Bio text (required) |')
  lines.push('| `avatarUrl` | string | Avatar image URL (required) |')
  lines.push('| `userNote` | string | Personal note / status text |')
  lines.push('| `profileOnlineAccentColor` | string or null | Online indicator color (#RRGGBB) |')
  lines.push('| `profileOnlinePulseEnabled` | boolean | Enable pulse animation on online indicator |')
  lines.push('')

  lines.push('**Theme and Appearance**')
  lines.push('')
  lines.push('| Field | Type | Description |')
  lines.push('|-------|------|-------------|')
  lines.push('| `themePreset` | string | Theme preset name (e.g. "basic") |')
  lines.push('| `themeCustomSurface` | object or null | Custom surface color config |')
  lines.push('| `customCss` | string | Custom CSS injected into the page |')
  lines.push('| `globalMouseTiltEnabled` | boolean | Enable mouse-tilt effect |')
  lines.push('| `globalMouseTiltGyroEnabled` | boolean | Enable gyroscope-based tilt |')
  lines.push('')

  lines.push('**Content and Display Text**')
  lines.push('')
  lines.push('| Field | Type | Description |')
  lines.push('|-------|------|-------------|')
  lines.push('| `currentlyText` | string | Label for "currently" section |')
  lines.push('| `earlierText` | string | Label for "earlier" section |')
  lines.push('| `adminText` | string | Label for admin link |')
  lines.push('| `hideActivityMedia` | boolean | Hide media in activity feed |')
  lines.push('| `displayTimezone` | string | Display timezone (e.g. "Asia/Shanghai") |')
  lines.push('')

  lines.push('**Hitokoto (Random Quote)**')
  lines.push('')
  lines.push('| Field | Type | Description |')
  lines.push('|-------|------|-------------|')
  lines.push('| `userNoteHitokotoEnabled` | boolean | Enable random quote as user note |')
  lines.push('| `userNoteHitokotoCategories` | array | Quote categories filter |')
  lines.push('| `userNoteHitokotoEncode` | string | Quote encode format |')
  lines.push('')

  lines.push('**Activity Feed Rules**')
  lines.push('')
  lines.push('| Field | Type | Description |')
  lines.push('|-------|------|-------------|')
  lines.push('| `appMessageRules` | array | Custom app display name rules |')
  lines.push('| `appMessageRulesShowProcessName` | boolean | Show process name in rules |')
  lines.push('| `appFilterMode` | "blacklist" or "whitelist" | App filtering strategy |')
  lines.push('| `appBlacklist` | array of strings | Apps to hide |')
  lines.push('| `appWhitelist` | array of strings | Apps to show exclusively |')
  lines.push('| `appNameOnlyList` | array of strings | Apps to show name only (no details) |')
  lines.push('| `captureReportedAppsEnabled` | boolean | Capture reported app names |')
  lines.push('| `mediaPlaySourceBlocklist` | array of strings | Media sources to block |')
  lines.push('| `activityRejectLockappSleep` | boolean | Reject lock/sleep app reports |')
  lines.push('')

  lines.push('**Steam Integration (partial)**')
  lines.push('')
  lines.push('| Field | Type | Description |')
  lines.push('|-------|------|-------------|')
  lines.push('| `steamEnabled` | boolean | Enable Steam status display |')
  lines.push('| `steamId` | string or null | Steam user ID |')
  lines.push('')
  lines.push('Note: `steamApiKey` is in the deny list and cannot be set via Skills.')
  lines.push('')

  lines.push('### Example: Update Theme Preset')
  lines.push('')
  lines.push('```')
  lines.push('PATCH /api/admin/settings')
  lines.push('Content-Type: application/json')
  lines.push('LLM-Skills-Mode: apikey')
  lines.push('LLM-Skills-Token: YOUR_TOKEN')
  lines.push('LLM-Skills-AI: YOUR_UNIQUE_AI_ID')
  lines.push('LLM-Skills-Scope: theme')
  lines.push('LLM-Skills-Request-Id: req-001')
  lines.push('')
  lines.push('{ "themePreset": "dark", "customCss": "body { --radius: 0.5rem; }" }')
  lines.push('```')
  lines.push('')
  lines.push('Response: `{ "success": true, "data": { ... } }` with the full updated config.')
  lines.push('')

  lines.push('## Deny List')
  lines.push('')
  lines.push('The following settings must NEVER be modified through the Skills channel:')
  lines.push('')
  lines.push('| Category | Fields |')
  lines.push('|----------|--------|')
  lines.push('| Redis config | `useNoSqlAsCacheRedis`, `redisCacheTtlSeconds` |')
  lines.push('| Activity update | `activityUpdateMode`, `processStaleSeconds`, `historyWindowMinutes` |')
  lines.push('| Steam Web API key | `steamApiKey` |')
  lines.push('| Device restrictions | `autoAcceptNewDevices`, `inspirationAllowedDeviceHashes` |')
  lines.push('| Page lock | `pageLockEnabled`, `pageLockPassword` |')
  lines.push('| hCaptcha | `hcaptchaEnabled`, `hcaptchaSiteKey`, `hcaptchaSecretKey` |')
  lines.push('')

  lines.push('## If Skills Is Not Configured')
  lines.push('')
  lines.push('When the user has not enabled Skills, guide them to:')
  lines.push('')
  lines.push('1. Open the admin panel')
  lines.push('2. Navigate to **Web Settings** then **Advanced Settings**')
  lines.push('3. Enable **Allow AI to use Skills for debugging and configuration**')
  lines.push('4. Select either OAuth or APIKEY mode')
  lines.push('5. Complete the authorization or key generation process')
  lines.push('')

  lines.push('## Important Notes')
  lines.push('')
  lines.push('- Always verify token validity via the `direct` endpoint before performing changes')
  lines.push('- Include `LLM-Skills-Request-Id` for audit trail on every request')
  lines.push('- Scope your requests appropriately: `feature` for feature toggles, `theme` for visual settings, `content` for content strategy')
  lines.push('- All changes are logged and reversible through the admin panel')
  lines.push('')

  return new NextResponse(lines.join('\n'), {
    status: 200,
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
      'Cache-Control': 'no-store',
    },
  })
}
